const ACTION = {
  PLACEMENTLIST_REQUEST: "PLACEMENTLIST_REQUEST",
  PLACEMENTLIST_SUCCESS: "PLACEMENTLIST_SUCCESS",
  PLACEMENTLIST_FAILURE: "PLACEMENTLIST_FAILURE",

  DOCUMENTS_REQUEST: "DOCUMENTS_REQUEST",
  DOCUMENTS_SUCCESS: "DOCUMENTS_SUCCESS",
  DOCUMENTS_FAILURE: "DOCUMENTS_FAILURE",

  LOCATIONS_REQUEST: "LOCATIONS_REQUEST",
  LOCATIONS_SUCCESS: "LOCATIONS_SUCCESS",
  LOCATIONS_FAILURE: "LOCATIONS_FAILURE",
}

export default ACTION
