const ACTION = {
  SET_COMPANY_DETAILS: "SET_COMPANY_DETAILS",

  LOAD_COMPANY_DETAILS_REQ: "LOAD_COMPANY_DETAILS_REQ",
  LOAD_COMPANY_DETAILS_SUCCESS: "LOAD_COMPANY_DETAILS_SUCCESS",
  LOAD_COMPANY_DETAILS_FAILURE: "LOAD_COMPANY_DETAILS_FAILURE",

}

export default ACTION
