const ACTION = {
  SET_NEW_CLIENT_BUSINESS_INFORMATION: "SET_NEW_CLIENT_BUSINESS_INFORMATION",

  SET_NEW_CLIENT_CONTACTS: "SET_NEW_CLIENT_CONTACTS",

  SET_NEW_CLIENT_ACCOUNTS: "SET_NEW_CLIENT_ACCOUNTS",

  SET_NEW_CLIENT_LOCATIONS: "SET_NEW_CLIENT_LOCATIONS",

  COUNTRIES_REQUEST: "COUNTRIES_REQUEST",
  COUNTRIES_SUCCESS: "COUNTRIES_SUCCESS",
  COUNTRIES_FAILURE: "COUNTRIES_FAILURE",
}

export default ACTION
