const initState = {
  businessInformation: {
    businessName: "",
    contactNumber: "",
    website: "",
    jobTerminationNotice: "",
    category: "",
    businessDisplayName: "",
    email: "",
    federalId: "",
    netTerms: "",
    fax: "",
    logo: "",
    permanentPlacement: {
      netTerms: "",
      commissionType: "",
      commission: "",
    },
    invoiceLocation: {
      line1: "",
      line2: "",
      city: "",
      state: "",
      country: "",
      zipCode: "",
    },
    status: false,
    countries: [],
    states: [],
  },
  contacts: {
    contactsList: [
      {
        key: 0,
        id: 0,
        representativeName: "",
        jobTitle: "",
        contactType: "",
        gender: "",
        email: "",
        mobile: "",
        workPhone: "",
        homePhone: "",
        line1: "",
        line2: "",
        country: "",
        state_name: "",
        city: "",
        zip: "",
        workPhoneExtension: "",
        isDraft: true,
      },
    ],
    status: false,
  },
  accounts: {
    jobTitle: "",
    email: "",
    homePhone: "",
    services: "",
    firstName: "",
    middleName: "",
    lastName: "",
    phoneNumber: "",
    mobileNumber: "",
    to: [],
    cc: [],
    bcc: [],
    helperText: {
      to: "",
      cc: "",
      bcc: "",
    },
    status: "",
    discountDetails: [
      {
        name: "",
        value: 0,
        type: "",
      },
    ],
    discountStatus: false,
  },
  locations: {
    locationsList: [
      {
        key: 0,
        id: 0,
        locationsline1: "",
        locationsline2: "",
        locationscountry: "",
        locationsstate_name: "",
        locationscity: "",
        locationszip: "",
        isDraft: true,
      },
    ],
    status: false,
  },
}

export default initState
